[package]
name = "prisma-client-rs"
version = "0.1.0"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "codegen",
    "derive"
]

[lib]
path = "lib.rs"

[dependencies]
serde_json = "1.0.50"
serde = { version = "1.0.106", features = ["serde_derive"] }
derive_more = "0.99.5"
itoa = "0.4.5"
chrono = "0.4"
ryu = "1.0.3"
prisma-codegen = { path = "./codegen" }
prisma-derive = { path = "./derive" }