[package]
name = "prisma-client-rs"
version = "0.1.0"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "codegen",
    "derive"
]

[lib]
path = "lib.rs"

[dependencies]
chrono = "0.4.11"
prisma-codegen = { path = "./codegen" }
prisma-derive = { path = "./derive" }