[package]
name = "prisma-client-derive"
version = "0.1.0"
authors = ["Seun <seunlanlege@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.17"
quote = "1.0.3"
itertools = "0.9.0"
